<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Market\Application\ProductCatalog;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260823020000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create products table and seed initial catalog items';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE IF NOT EXISTS products ('
            . 'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'slug VARCHAR(120) NOT NULL, '
            . 'name VARCHAR(255) NOT NULL, '
            . 'definition TEXT NOT NULL, '
            . 'category VARCHAR(50) NOT NULL, '
            . 'family_slug VARCHAR(120) NOT NULL, '
            . 'family_name VARCHAR(255) NOT NULL, '
            . 'image VARCHAR(512) DEFAULT NULL, '
            . 'image_credit VARCHAR(255) DEFAULT NULL, '
            . 'image_source VARCHAR(1024) DEFAULT NULL, '
            . 'specifications JSON NOT NULL, '
            . 'created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, '
            . 'updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, '
            . 'PRIMARY KEY(id))'
        );
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_products_slug ON products (slug)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_products_category ON products (category)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_products_family_slug ON products (family_slug)');

        $catalog = new ProductCatalog();
        $now = (new \DateTimeImmutable('2026-08-23 00:00:00', new \DateTimeZone('UTC')))->format('Y-m-d H:i:sP');

        foreach ($catalog->seedProducts() as $product) {
            $familySlug = $catalog->familySlug($product);
            [$image, $credit, $source] = $catalog->familyImage($familySlug, $product->category);

            $familyName = match ($product->category) {
                'smartphones' => 'Apple ' . ($product->specifications['generation'] ?? $product->name),
                'laptops' => sprintf(
                    '%s %s %s',
                    $product->specifications['line'] ?? 'MacBook Air',
                    $product->specifications['display'] ?? '',
                    $product->specifications['chip'] ?? ''
                ),
                'ram' => $product->specifications['family_name'] ?? 'RAM Memory',
                'cars' => 'Peugeot 206 CC',
                default => $product->name,
            };

            $this->addSql(
                'INSERT INTO products ('
                . 'slug, name, definition, category, family_slug, family_name, '
                . 'image, image_credit, image_source, specifications, created_at, updated_at) '
                . 'VALUES ('
                . ':slug, :name, :definition, :category, :family_slug, :family_name, '
                . ':image, :image_credit, :image_source, :specifications, :created_at, :updated_at) '
                . 'ON CONFLICT (slug) DO NOTHING',
                [
                    'slug' => $product->slug,
                    'name' => $product->name,
                    'definition' => $product->definition,
                    'category' => $product->category,
                    'family_slug' => $familySlug,
                    'family_name' => trim($familyName),
                    'image' => $image,
                    'image_credit' => $credit,
                    'image_source' => $source,
                    'specifications' => json_encode($product->specifications, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE),
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS products');
    }
}
