<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260824030000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create price_alerts table for double opt-in price drop subscriptions';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE IF NOT EXISTS price_alerts ('
            . 'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'product_slug VARCHAR(100) NOT NULL, '
            . 'email VARCHAR(255) NOT NULL, '
            . 'target_price_grosz INT DEFAULT NULL, '
            . 'verification_token VARCHAR(64) NOT NULL, '
            . 'unsubscribe_token VARCHAR(64) NOT NULL, '
            . 'is_verified BOOLEAN NOT NULL DEFAULT FALSE, '
            . 'verified_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, '
            . 'ip_hash VARCHAR(64) NOT NULL, '
            . 'locale VARCHAR(10) NOT NULL DEFAULT \'pl\', '
            . 'created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, '
            . 'last_notified_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, '
            . 'last_notified_price_grosz INT DEFAULT NULL, '
            . 'status VARCHAR(20) NOT NULL DEFAULT \'pending\', '
            . 'PRIMARY KEY(id))'
        );
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_alerts_verification_token ON price_alerts (verification_token)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_alerts_unsubscribe_token ON price_alerts (unsubscribe_token)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_alerts_product_slug ON price_alerts (product_slug)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_alerts_email ON price_alerts (email)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_alerts_status ON price_alerts (status)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON price_alerts (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS price_alerts');
    }
}
